# Produktiv-Konfiguration für maximale Datensammlung
TIERS = ["SILVER", "GOLD", "PLATINUM", "EMERALD", "DIAMOND"]
DIVISIONS = ["I", "II", "III", "IV"]

INCLUDE_MASTER = True
MASTER_SAMPLE_FRAC = 0.30

TARGET_SUMMONERS_PER_BUCKET = 50
MAX_MATCH_IDS_PER_PUUID = 100
MIN_YEAR = 2023

MAX_WORKERS = 8
REQUEST_TIMEOUT = 20
REQS_PER_SEC = 12

RUN_DEBUG_PROBE = False
USE_BOOTSTRAP = False
